<?php

namespace App\Form;

use App\Entity\PropertyResearch;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyResearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('maxPrice', IntegerType::class,
            [
                'required' => false,
                'label' => false,
                'attr' =>
                [
                    'placeholder' => 'Max Price'
                ]
            ])

            ->add('minSurface', IntegerType::class,
                [
                    'required' => false,
                    'label' => false,
                    'attr' =>
                        [
                            'placeholder' => 'Min Surface'
                        ]
                ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PropertyResearch::class,
            'method' => 'get',
            'csrf_protection' => false
        ]);
    }

    public  function getBlockPrefix(): string
    {
        return ''; // TODO: Change the autogenerated stub
    }
}
